### ISSUE TITLE
启动报错：Module build failed (from ./node_modules/babel-loader/lib/index.js)

### ISSUE THREAD

**Issue by zhuyee** [WX-DongXing/terminator#10]
你好，按照文档方法，安装了`yarn`，然后执行`yarn install`，启动项目后报错：
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in D:\IDEA3.2_pro\OpenSource\terminator\node_modules\@babel\helper-compilation-targets\package.jso
n
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\IDEA3.2_pro\OpenSource\terminator\node_modules\@babel\preset-env\lib\debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (D:\IDEA3.2_pro\OpenSource\terminator\node_modules\@babel\preset-env\lib\index.js:11:14)

 @ multi (webpack)-dev-server/client?本地的IP/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```
我本地环境：
- node：v14.15.4
- npm：6.14.10
- yarn：1.22.10

参考网上的说是有模块丢失，也有的说是版本问题：[参考文章](https://stackoverflow.com/questions/62081761/error-err-package-path-not-exported-no-exports-main-resolved-inbabel-helpe)

请问这个怎么解决？

**Comment by WX-DongXing** [comment]
使用你提供的版本和环境未复现这个问题，确认是不是因为网络原因导致依赖未安装完全

**Comment by zhuyee** [comment]
> 使用您提供的版本和环境未复现这个问题，确认是不是因为网络原因导致未安装完全

谢谢 :blush: 我已经解决问题了，重新拉取的项目，安装依赖，不过依赖出现以下警告：
```bash
yarn install v1.22.10
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid r
esolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > vue-animation-timeline@0.2.5" has unmet peer dependency "@vue/composition-api@^1.0.0-beta.20".
warning " > @vue/eslint-config-standard@5.1.2" has incorrect peer dependency "eslint@>=6.2.2".
warning " > @vue/eslint-config-standard@5.1.2" has incorrect peer dependency "eslint-plugin-vue@>= 6.1.2".
warning "@vue/eslint-config-standard > eslint-config-standard@14.1.1" has incorrect peer dependency "eslint@>=6.2.2".
warning "@vue/eslint-config-standard > eslint-import-resolver-webpack@0.12.2" has unmet peer dependency "webpack@>=1.11.0".
warning " > less-loader@5.0.0" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > lodash-webpack-plugin@0.11.6" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.1.0".
[4/4] Building fresh packages...
success Saved lockfile.
```
接着删除了对应的`package-lock.json`，有些不适配的采取了网上的办法：`yarn config set ignore-engines true`，然后重新拉取依赖，启动项目就正常访问了。

大佬有时间的话，能不能把组件开发的思路大致说一下 :stuck_out_tongue_winking_eye:

**Comment by WX-DongXing** [comment]
后续有时间的话将会重新整理说明。
